"""add external_ref to raw_messages

Revision ID: 159a1c861269
Revises: 917faced2323
Create Date: 2026-07-27 18:23:47.724977

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "159a1c861269"
down_revision: str | Sequence[str] | None = "917faced2323"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("raw_messages", sa.Column("external_ref", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("raw_messages", "external_ref")
    # ### end Alembic commands ###
